set(3DSCANNER_CORE_FOUND TRUE)

find_path(3DSCANNER_CORE_INCLUDE_DIR "./include")
find_library(3DSCANNER_CORE_LIBRARY NAME lib3DScaner-core.a PATHS "./build")

set(3DSCANNER_CORE_INCLUDE_DIR ${3DSCANNER_CORE_INCLUDE_DIR})
set(3DSCANNER_CORE_LIBRARY ${3DSCANNER_CORE_LIBRARY})

mark_as_advanced(3DSCANNER_CORE_INCLUDE_DIR 3DSCANNER_CORE_LIBRARY)
